version: '2'

services:
    static:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./build/client/:/static/
        ports:
            - "${HTTP}:80"
        depends_on:
            - app
    app:
        build: ./
        environment:
            # Avoiding a .env file here to show warnings
            # when these variables are missing
            - TO=${TO}
            - FROM=${FROM}
            - PASS=${PASS}
